### ISSUE TITLE
DSCP marking on response packets

### ISSUE THREAD

**Issue by mskumarece** [domoslabs/twamp-light#2]
Hi, 
i am trying to use twamp-light-server ./twamp-light-server  -P 64364 -t 0 --no-sync
Client is marking the DSCP=46, ECN=0(0xb8).
When server responds/reflects it DSCP=2,ECN=2 (0x0a). 
How to make server respond with same DSCP as the client

**Comment by mskumarece** [comment]
@vladim0105 vladim0105-domos

**Comment by mskumarece** [comment]
@vladim0105  Curious to find the license for this project., can you please update. Thnaks

**Comment by vladim0105** [comment]
> @vladim0105  Curious to find the license for this project., can you please update. Thnaks

I don't work at Domos anymore, perhaps @bjornite can help you?
